- name: configure frontend server
  become: yes
  hosts: frontend
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.nginx:
      name: nginx
      state: started
      enabled: yes